OUTPUT_DIR: "/data/Projects_Data/SeqNet-DA/exp/exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/data/PersonSearch/CUHK-SYSU"
SOLVER:
  MAX_EPOCHS: 20
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000